<#PSScriptInfo

.DESCRIPTION Lists the Events from a LogFile generated by Write-Log

.VERSION 1.0.0.0

.GUID 2e148d97-aa8b-47bb-8542-3e8f64e9753c

.AUTHOR Tom Stryhn

.COMPANYNAME Tom Stryhn

.COPYRIGHT 2023 (c) Tom Stryhn

.TAGS PowerShell Log

.LICENSEURI https://github.com/tomstryhn/PowerShell/blob/main/LICENSE

.PROJECTURI https://github.com/tomstryhn/PowerShell/Universal/Get-Log/

#>

function Get-Log {
    [CmdletBinding()]
    param (
        # The Path to the actual LogFile
        [Parameter(
            Mandatory                       = $true,
            Position                        = 0
        )]
        [ValidateScript(
            {
                if ($_){  Test-Path $_}
            })]
        [string]
        $LogPath
    )
    
    process {
        # Simply reads the Content of the LogFile as CSV Content and adds Headers to the Data
        Get-Content -Path $LogPath | ConvertFrom-Csv -Delimiter "`t" -Header 'TimeStamp','LogLevel','Message'
    }
}
